max_obstacle_height: 0.60 

footprint: [[0.4064, 0.3556],[0.4064,-0.3556],[-0.4064,-0.3556],[-0.4064,0.3556]]

map_type: voxel

obstacle_layer:
  enabled:              true
  max_obstacle_height:  2.0
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             2
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  true
  obstacle_range: 2.5
  raytrace_range: 3.0
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  publish_voxel_map: false
  observation_sources:  scan groundPoints obstaclePoints
  scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    expected_update_rate: 0.1
    inf_is_valid: true
  groundPoints:
    data_type: PointCloud2
    topic: /rtabmap/ground
    marking: false
    clearing: true
  obstaclePoints:
    data_type: PointCloud2
    topic: /rtabmap/proj_obstacles
    marking: true
    clearing: false
    

inflation_layer:
  enabled:              true
  cost_scaling_factor:  5.0
  inflation_radius:     0.5 

static_layer:
  enabled:              true