<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="rrbot">
    <!--<xacro:include filename="$(find cse468_final_bot)/urdf/gripper.xacro" />-->
    <!-- Constants for robot dimensions -->
    <xacro:property name="width" value="0.1" />
    <xacro:property name="height1" value="1" />
    <xacro:property name="height2" value=".5" />
    <xacro:property name="height3" value=".5" />
    <xacro:property name="axle_offset" value="0.05" />
    <xacro:property name="damp" value="0.7" />
    <!-- Base Link -->
    <joint name="gripper_extension" type="fixed">
        <parent link="base_link"/>
        <child link="base_link2"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>
    <link name="base_link2">
        <visual>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height1}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height1}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${height1/2}" rpy="0 0 0" />
            <mass value="1" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>
    <!-- Joint between Base Link and Middle Link -->
    <joint name="joint_base_mid" type="revolute">
        <parent link="base_link2" />
        <child link="mid_link" />
        <origin xyz="0 ${width} ${height1 - axle_offset}" rpy="0 0  0" />
        <axis xyz="0 1 0" />
        <dynamics damping="${damp}" />
        <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14" />
    </joint>
    <!-- Middle Link -->
    <link name="mid_link">
        <visual>
            <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height2}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height2}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${height2/2 - axle_offset}" rpy="0 0 0" />
            <mass value="1" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>
    <!-- Joint between Middle Link and Top Link -->
    <joint name="joint_mid_top" type="revolute">
        <parent link="mid_link" />
        <child link="top_link" />
        <origin xyz="0 ${width} ${height2 - axle_offset*2}" rpy="0 0  0" />
        <axis xyz="0 1 0" />
        <dynamics damping="${damp}" />
        <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14" />
    </joint>
    <!-- Top Link -->
    <link name="top_link">
        <visual>
            <origin xyz="0 0 ${height3/2 - axle_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height3}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${height3/2 - axle_offset}" rpy="0 0 0" />
            <geometry>
                <box size="${width} ${width} ${height3}" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${height3/2 - axle_offset}" rpy="0 0 0" />
            <mass value="1" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </link>
    <joint name="left_gripper_joint" type="revolute">
        <parent link="top_link"/>
        <child link="left_gripper"/>
        <origin xyz="0 0 ${height2 - axle_offset}" rpy="0 -1.57 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="30.0" lower="-0.548" upper="0.0" velocity="0.1"/>
    </joint>
    <link name="left_gripper">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://urdf_tutorial/meshes/l_finger.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
    </link>
    <joint name="left_tip_joint" type="fixed">
        <parent link="left_gripper"/>
        <child link="left_tip"/>
    </joint>
    <link name="left_tip">
        <visual>
            <origin rpy="0 0 0" xyz="0.09137 0.00495 0"/>
            <geometry>
                <mesh 
          filename="package://urdf_tutorial/meshes/l_finger_tip.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
    </link>
    <joint name="right_gripper_joint" type="revolute">
        <parent link="top_link"/>
        <child link="right_gripper"/>
        <origin xyz="0 0 ${height2 - axle_offset}" rpy="0 -1.57 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="30.0" lower="0.0" upper="0.548" velocity="0.5"/>
    </joint>
    <link name="right_gripper">
        <visual>
            <origin rpy="-3.1415 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://urdf_tutorial/meshes/l_finger.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
    </link>
    <joint name="right_tip_joint" type="fixed">
        <parent link="right_gripper"/>
        <child link="right_tip"/>
    </joint>
    <link name="right_tip">
        <visual>
            <origin rpy="-3.1415 0 0" xyz="0.09137 0.00495 0"/>
            <geometry>
                <mesh filename="package://urdf_tutorial/meshes/l_finger_tip.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
    </link>
</robot>