<?xml version="1.0"?>
<robot name="drivebase_macros" xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="drivebase_length" value="0.8"/>
    <xacro:property name="drivebase_width" value="0.7"/>
    <xacro:property name="drivebase_height" value="0.1"/>

    <xacro:property name="wheel_radius" value="0.0762"/>
    <xacro:property name="wheel_thickness" value="0.0508"/>

    <xacro:property name="wheel_height" value="-0.01"/>
    <xacro:property name="center_wheel_drop" value="0.003175"/>
    <xacro:property name="wheel_base_seperation" value="0.03"/>
    <xacro:property name="front_rear_spacing" value="0.05"/>

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <xacro:macro name="wheel" params="side position reflect">
        <link name="${position}_${side}_wheel">
            <visual>
                <geometry>
                    <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                </geometry>
                <origin rpy="0 ${pi / 2} ${pi / 2}" xyz="0 0 0"/>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                </geometry>
                <origin rpy="0 ${pi / 2} ${pi / 2}" xyz="0 0 0"/>
            </collision>
            <inertial>
                <mass value="0.2630836"/>
                <inertia ixx="0.000438" ixy="0.0" ixz="0.0" iyy="0.000438" iyz="0.0" izz="0.000763"/>
            </inertial>
        </link>

        <joint name="base_to_${position}_${side}_wheel" type="continuous">
            <parent link="base_link"/>
            <child link="${position}_${side}_wheel"/>
            <xacro:if value="${position == 'front'}">
                <origin xyz="${(drivebase_length / 2) - front_rear_spacing} ${((drivebase_width / 2) + wheel_base_seperation) * reflect} ${wheel_height}"/>
            </xacro:if>
            <xacro:if value="${position == 'center'}">
                <origin xyz="0 ${((drivebase_width / 2) + wheel_base_seperation) * reflect} ${wheel_height - center_wheel_drop}"/>
            </xacro:if>
            <xacro:if value="${position == 'rear'}">
                <origin xyz="${-1 * ((drivebase_length / 2) - front_rear_spacing)} ${((drivebase_width / 2) + wheel_base_seperation) * reflect} ${wheel_height}"/>
            </xacro:if>
            <axis xyz="0 1 0"/>
        </joint>

        <transmission name="${position}_${side}_wheel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${position}_${side}_wheel_motor">
                <mechanicalReduction>7.44</mechanicalReduction>
            </actuator>
            <joint name="base_to_${position}_${side}_wheel">
                <hardwareInterface>VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

        <gazebo reference="${position}_${side}_wheel">
            <mu1 value="200.0"/>
            <mu2 value="100.0"/>
            <kp value="10000000.0" />
            <kd value="1.0" />
        <material>Gazebo/Grey</material>
    </gazebo>
    </xacro:macro>

    <xacro:macro name="robot_side" params="side reflect">
        <xacro:wheel side="${side}" position="front" reflect="${reflect}"/>
        <xacro:wheel side="${side}" position="center" reflect="${reflect}"/>
        <xacro:wheel side="${side}" position="rear" reflect="${reflect}"/>
    </xacro:macro>
</robot>