<?xml version="1.0"?>
<root xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find cse468_final_bot)/urdf/inertia.xacro" />
    <xacro:property name="front" value="1" />
    <xacro:property name="middle" value="0" />
    <xacro:property name="rear" value="-1" />
    <xacro:property name="left" value="1" />
    <xacro:property name="right" value="-1" />
    <xacro:property name="no_drop" value="0" />
    <xacro:property name="drop" value="-1" />
    <xacro:property name="high_friction" value="200.0" />
    <xacro:property name="medium_friction" value="100.0" />
    <xacro:property name="low_friction" value="1.0" />
    <xacro:property name="pivot_radius" value="0.025" />
    <xacro:property name="pivot_height" value="0.025" />
    <xacro:property name="pivot_mass" value="1.0" />

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <xacro:macro name="six_wheel_diff_drive" params="name parent z_offset drop_wheel_height wheel_separation wheelbase_length wheel_radius wheel_width wheel_mass">
        <xacro:macro name="diff_wheel" params=" parent2 prefix side fntctrbck drop friction mimic mimic_parent">
            <link name="${prefix}_diff_wheel">
                <visual>
                    <geometry>
                        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                    </geometry>
                    <origin xyz="0 0 0"/>
                    <material name="blue"/>
                </visual>
                <collision>
                    <geometry>
                        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                    </geometry>
                    <origin xyz="0 0 0"/>
                </collision>
                <inertial>
                    <mass value="${wheel_mass}"/>
                    <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
                    <origin xyz="0 0 0"/>
                </inertial>
            </link>
            <joint name="${parent2}_to_${prefix}_diff_wheel" type="continuous">
                <parent link="${parent2}"/>
                <child link="${prefix}_diff_wheel"/>
                <axis xyz="0 0 ${-1*side}"/>
                <origin rpy="${side*pi/2} 0 0" xyz="${fntctrbck*(wheelbase_length/2)} ${side*(wheel_separation/2)} ${z_offset+drop*drop_wheel_height}"/>
                <xacro:if value="${mimic != 'NONE'}">
                    <mimic joint="${mimic_parent}_to_${mimic}_diff_wheel"/>
                </xacro:if>
            </joint>
            <transmission name="${prefix}_diff_wheel_trans">
                <type>transmission_interface/SimpleTransmission</type>
                <actuator name="${prefix}_diff_wheel_motor">
                    <mechanicalReduction>1</mechanicalReduction>
                </actuator>
                <joint name="${parent2}_to_${prefix}_diff_wheel">
                    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                </joint>
            </transmission>
            <gazebo reference="${prefix}_diff_wheel">
                <mu1 value="${friction}"/>
                <mu2 value="${friction}"/>
                <kp value="10000000.0"/>
                <kd value="1.0" />
                <material>Gazebo/gray</material>
            </gazebo>
        </xacro:macro>
        <xacro:diff_wheel parent2="${parent}" prefix="fl" side="${left}" fntctrbck="${front}" drop="${no_drop}" friction="${low_friction}" mimic="ml" mimic_parent="base_link"/>
        <xacro:diff_wheel parent2="${parent}" prefix="ml" side="${left}" fntctrbck="${middle}" drop="${drop}" friction="${high_friction}" mimic="NONE" mimic_parent="base_link"/>
        <xacro:diff_wheel parent2="${parent}" prefix="rl" side="${left}" fntctrbck="${rear}" drop="${no_drop}" friction="${low_friction}"  mimic="ml" mimic_parent="base_link"/>
        <xacro:diff_wheel parent2="${parent}" prefix="fr" side="${right}" fntctrbck="${front}" drop="${no_drop}" friction="${low_friction}"  mimic="mr" mimic_parent="base_link"/>
        <xacro:diff_wheel parent2="${parent}" prefix="mr" side="${right}" fntctrbck="${middle}" drop="${drop}" friction="${high_friction}"  mimic="NONE" mimic_parent="base_link"/>
        <xacro:diff_wheel parent2="${parent}" prefix="rr" side="${right}" fntctrbck="${rear}" drop="${no_drop}" friction="${low_friction}"  mimic="mr" mimic_parent="base_link"/>
    </xacro:macro>
</root>