<?xml version="1.0"?>
<robot name="kinect" xmlns:xacro="http://ros.org/wiki/xacro">
    <joint name="camera_joint" type="fixed">
        <axis xyz="0.0 0.0 0.0"/>
        <origin xyz="${drivebase_length/2} 0 ${drivebase_height + .01}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="camera_link"/>
    </joint>

    <link name="camera_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://cse468_final_bot/meshes/kinect.dae"/>
            </geometry>
        </visual>

        <inertial>
            <mass value="0.05" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>
</robot>